working on listing

diff --git a/baphomet b/baphomet
--- a/baphomet
+++ b/baphomet
@@ -44,6 +44,14 @@ containsElement () {
     return 1
 }
 
+push()
+{
+    #    http://cfajohnson.com
+    local arrayname=${1:?Array name required} #val=$2
+    shift
+    eval "$arrayname=( \"\$@\" \"\${$arrayname[@]}\" )"
+}
+
 userTest () {
     [[ ${#@} -ne 0 ]] && USER="${1}"
     :
@@ -151,7 +159,7 @@ do
         -u|--user)
             UZR="${2}"
             [[ ${#UZR} -eq 0 ]] && \
-                    printf 'A user must be specified!\n' && exit 1
+                printf 'A user must be specified!\n' && exit 1
             if ! userTest "${UZR}"; then exit 1; fi
             :
             shift 2
@@ -201,7 +209,7 @@ do
                 printf '|- No daemons found.\n';exit
             fi
 
-            printf '|- \e[33m%s\e[0m\n' "${arrDaemons[@]/%/=}"
+            printf '|- \e[33m%s=\e[0m\n' "${arrDaemons[@]//\!/\/}"
             if  [[ $INTERACTIVE == TRUE ]]; then
                 printf '\n\n\e[31mWhat do you desire?\e[0m\n'
                 select option in 'Return' 'Quit'
@@ -221,18 +229,22 @@ do
         --list-very-verbose|-lvv)
             query_daemon LISP_BUFFER_COUNT; arrBuffers=("${result[@]}")
             query_daemon LISP_PID; arr_pids=("${result[@]}")
-
+            :
+            push arrDaemons "Daemon"
+            push arrBuffers "Files"
+            push arr_pids "PID"
             printf '\e[37;4;2m%s\e[0m\n\n' "${EMACS_SOCKET_DIR}"
-            printf '\e[37;4;2m%-20s %-23s %-20s\e[0m\n' "Daemon" "File #" "PID"
-            paste <(printf '|- \e[33m%-20s\e[0m\n' "${arrDaemons[@]/%/=}") <(printf '%-20s\n' "${arrBuffers[@]}") <(printf '%-20s\n' "${arr_pids[@]}")
+#            printf '\e[37;4;2m%-20s %-23s %-20s\e[0m\n' "Daemon" "File #" "PID"
+            paste <(printf '|- \e[33m%s=\e[0m\n' "${arrDaemons[@]//\!/\/}") <(printf '%-20s\n' "${arrBuffers[@]}") <(printf '%-20s\n' "${arr_pids[@]}") | column -t
             exit
             ;;
         --list-verbose|-lv)
             query_daemon LISP_BUFFER_COUNT; arrBuffers=("${result[@]}")
             :
+            push arrDaemons "Daemon"
+            push arrBuffers "Files"
             printf '\e[37;4;2m%s\e[0m\n\n' "${EMACS_SOCKET_DIR}"
-            printf '\e[37;4;2m%-20s %s\e[0m\n' "Daemon" "File #"
-            paste <(printf '|- \e[33m%-20s\e[0m\n' "${arrDaemons[@]/%/=}") <(printf '%s\n' "${arrBuffers[@]}")
+            paste <(printf '|- \e[33m%s=\e[0m\n' "${arrDaemons[@]//\!/\/}") <(printf '%s\n' "${arrBuffers[@]}") | column -t
             exit
             ;;
         --list-buffers|-lb)
@@ -390,50 +402,50 @@ EOF
         *)
             break;
             ;;
-    esac
-    [[ "${#@}" -gt 0 ]] && shift 2
-done
+                                                              esac
+                                                              [[ "${#@}" -gt 0 ]] && shift 2
+                                                             done
 
 
 
-case ${@:1:1} in
-    -i|--interactive)
-        printf '\e[33m%.0s-' {1..20}; printf '\n'
-        printf '     MAIN MENU\n'
-        printf '%.0s-' {1..20};  printf '\e[0m\n'
-        select option in ${arrDaemons[@]:+'List'} ${arrDaemons[@]:+'Join'} 'Summon' 'Quit'
-        do
-            case $option in
-                'List')
-                    INTERACTIVE=TRUE exec "${0}" -l
-                    ;;
-                'Join')
-                    INTERACTIVE=TRUE exec "${0}" -j
-                    ;;
-                'Summon')
-                    printf '\n\e[31mName your daemon\e[0m: '
-                    read -r daemon
-                    [[ "${daemon^^}" == "BAPHOMET" ]] && printf 'No.\n' && exit 1
-                    INTERACTIVE=TRUE exec "${0}" -s "${daemon}"
-                    ;;
-                'Quit')
-                    printf '\nBye.\n'
-                    exit
-                    ;;
-                *)
-                    printf 'Invalid choice.\n'
-                    ;;
-            esac
-        done
-        ;;
-esac
+                                                              case ${@:1:1} in
+                                                                  -i|--interactive)
+                                                                      printf '\e[33m%.0s-' {1..20}; printf '\n'
+                                                                      printf '     MAIN MENU\n'
+                                                                      printf '%.0s-' {1..20};  printf '\e[0m\n'
+                                                                      select option in ${arrDaemons[@]:+'List'} ${arrDaemons[@]:+'Join'} 'Summon' 'Quit'
+                                                                      do
+                                                                          case $option in
+                                                                              'List')
+                                                                                  INTERACTIVE=TRUE exec "${0}" -l
+                                                                                  ;;
+                                                                              'Join')
+                                                                                  INTERACTIVE=TRUE exec "${0}" -j
+                                                                                  ;;
+                                                                              'Summon')
+                                                                                  printf '\n\e[31mName your daemon\e[0m: '
+                                                                                  read -r daemon
+                                                                                  [[ "${daemon^^}" == "BAPHOMET" ]] && printf 'No.\n' && exit 1
+                                                                                  INTERACTIVE=TRUE exec "${0}" -s "${daemon}"
+                                                                                  ;;
+                                                                              'Quit')
+                                                                                  printf '\nBye.\n'
+                                                                                  exit
+                                                                                  ;;
+                                                                              *)
+                                                                                  printf 'Invalid choice.\n'
+                                                                                  ;;
+                                                                          esac
+                                                                      done
+                                                                      ;;
+                                                              esac
 
 
 
-case ${@:1:1} in
-    --shell)
-        exec bash --rcfile <(read -r baphomet_shell < \
-                                  <(printf '%s' "PS1=$'\\e[38;5;196m\\u2605 BAPHOMET >\\e[0m ' ;\
+                                                              case ${@:1:1} in
+                                                                  --shell)
+                                                                      exec bash --rcfile <(read -r baphomet_shell < \
+                                                                                                <(printf '%s' "PS1=$'\\e[38;5;196m\\u2605 BAPHOMET >\\e[0m ' ;\
 trap \"printf '%s\\n\\n' $'\\111\\47\\154\\154\\40 \\142\\145\\40 \\163\\145\\145\\151\\156\\147\\40 \\171\\157\\165\\56'; tput clear \"  EXIT;\
 cd $EMACS_SOCKET_DIR;\
 tput clear;\
@@ -450,13 +462,13 @@ alias kill-all=\"${0} -ka\";\
 alias ka=kill-all;\
 alias join=\"${0} -j\";\
 "); printf '%s' "${baphomet_shell}") -i
-        ;;
-esac
+                                                                      ;;
+                                                              esac
 
-socket="${arrSockets[0]}"
-daemon="$(basename "${socket}")"
-[[ ${#socket} -gt 0 ]] && \
-    EMACS_BUFFER_NAME=${1:-'*BAPHOMET WELCOMES YOU*'} exec "${0}" -j "${daemon}"
+                                                              socket="${arrSockets[0]}"
+                                                              daemon="$(basename "${socket}")"
+                                                              [[ ${#socket} -gt 0 ]] && \
+                                                                  EMACS_BUFFER_NAME=${1:-'*BAPHOMET WELCOMES YOU*'} exec "${0}" -j "${daemon}"
 
-printf '\e[0;36m%s\e[0m\n' "No daemons found. Let's get interactive."
-exec "${0}" --interactive
+                                                              printf '\e[0;36m%s\e[0m\n' "No daemons found. Let's get interactive."
+                                                              exec "${0}" --interactive
